In [8]:
from tensorflow.keras.preprocessing.text import one_hot 
import numpy as np 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential 
from tensorflow.keras.utils import pad_sequences

In [18]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'Iam a robot',
    'Iam not a robot',
    'understand the meaning of words',
    'your name please',
    'nothing is impossible if you try again'
]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'Iam a robot',
 'Iam not a robot',
 'understand the meaning of words',
 'your name please',
 'nothing is impossible if you try again']

In [19]:
len(sent)

8

In [20]:
# define vocabularay size
vocab_size = 10000

In [21]:
for words in sent :
    print (words)
    print(one_hot(words,vocab_size))
    

the glass of milk
[8275, 646, 5607, 2012]
the glass of juice
[8275, 646, 5607, 7365]
the cup of tea
[8275, 5702, 5607, 6848]
Iam a robot
[2347, 6826, 7421]
Iam not a robot
[2347, 9330, 6826, 7421]
understand the meaning of words
[3546, 8275, 447, 5607, 5686]
your name please
[8776, 1312, 8259]
nothing is impossible if you try again
[7565, 4702, 8655, 4801, 3402, 4083, 7972]


In [22]:
# one hot represetataion of sentences
one_hot_rep = [one_hot(words,vocab_size) for words in sent]
one_hot_rep

[[8275, 646, 5607, 2012],
 [8275, 646, 5607, 7365],
 [8275, 5702, 5607, 6848],
 [2347, 6826, 7421],
 [2347, 9330, 6826, 7421],
 [3546, 8275, 447, 5607, 5686],
 [8776, 1312, 8259],
 [7565, 4702, 8655, 4801, 3402, 4083, 7972]]

In [23]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.uitils import pad_sequences
from tensorflow.keras.models import Sequential


In [24]:
# to make all the sentences as equal in length use padding(pad_sequences)
# use padding to make all the sentences as equal in length

# define the length
sent_length = 10
embedded_doc = pad_sequences(one_hot_rep,padding="pre",maxlen=sent_length)
embedded_doc


array([[   0,    0,    0,    0,    0,    0, 8275,  646, 5607, 2012],
       [   0,    0,    0,    0,    0,    0, 8275,  646, 5607, 7365],
       [   0,    0,    0,    0,    0,    0, 8275, 5702, 5607, 6848],
       [   0,    0,    0,    0,    0,    0,    0, 2347, 6826, 7421],
       [   0,    0,    0,    0,    0,    0, 2347, 9330, 6826, 7421],
       [   0,    0,    0,    0,    0, 3546, 8275,  447, 5607, 5686],
       [   0,    0,    0,    0,    0,    0,    0, 8776, 1312, 8259],
       [   0,    0,    0, 7565, 4702, 8655, 4801, 3402, 4083, 7972]],
      dtype=int32)

In [25]:
embedded_doc = pad_sequences(one_hot_rep,padding="post",maxlen=sent_length)
embedded_doc

array([[8275,  646, 5607, 2012,    0,    0,    0,    0,    0,    0],
       [8275,  646, 5607, 7365,    0,    0,    0,    0,    0,    0],
       [8275, 5702, 5607, 6848,    0,    0,    0,    0,    0,    0],
       [2347, 6826, 7421,    0,    0,    0,    0,    0,    0,    0],
       [2347, 9330, 6826, 7421,    0,    0,    0,    0,    0,    0],
       [3546, 8275,  447, 5607, 5686,    0,    0,    0,    0,    0],
       [8776, 1312, 8259,    0,    0,    0,    0,    0,    0,    0],
       [7565, 4702, 8655, 4801, 3402, 4083, 7972,    0,    0,    0]],
      dtype=int32)

In [26]:
print('vocabulary size : ',vocab_size)
print('length of sentence : ',sent_length)
print('embedded document : ',embedded_doc)


vocabulary size :  10000
length of sentence :  10
embedded document :  [[8275  646 5607 2012    0    0    0    0    0    0]
 [8275  646 5607 7365    0    0    0    0    0    0]
 [8275 5702 5607 6848    0    0    0    0    0    0]
 [2347 6826 7421    0    0    0    0    0    0    0]
 [2347 9330 6826 7421    0    0    0    0    0    0]
 [3546 8275  447 5607 5686    0    0    0    0    0]
 [8776 1312 8259    0    0    0    0    0    0    0]
 [7565 4702 8655 4801 3402 4083 7972    0    0    0]]


In [27]:
# feature diamention for wordembedding layer (each and every words in the sentences)
# mostly use feature diamention as 300
feature_dim = 10

In [29]:
# train the embedding layer
model = Sequential()
model.add(Embedding(vocab_size,feature_dim,input_length=sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [34]:
embedded_doc

array([[8275,  646, 5607, 2012,    0,    0,    0,    0,    0,    0],
       [8275,  646, 5607, 7365,    0,    0,    0,    0,    0,    0],
       [8275, 5702, 5607, 6848,    0,    0,    0,    0,    0,    0],
       [2347, 6826, 7421,    0,    0,    0,    0,    0,    0,    0],
       [2347, 9330, 6826, 7421,    0,    0,    0,    0,    0,    0],
       [3546, 8275,  447, 5607, 5686,    0,    0,    0,    0,    0],
       [8776, 1312, 8259,    0,    0,    0,    0,    0,    0,    0],
       [7565, 4702, 8655, 4801, 3402, 4083, 7972,    0,    0,    0]],
      dtype=int32)

In [33]:
embedded_doc[0][0]

8275

In [36]:
model.predict(embedded_doc[0])

1/1 [==============================] - 0s 70ms/step


array([[-0.04573219, -0.03658372, -0.0093651 , -0.03511826,  0.04394332,
         0.04861123, -0.02257059,  0.02043867,  0.00202392, -0.01176693],
       [ 0.03105364,  0.00266211, -0.04327337, -0.01850931, -0.01866363,
         0.04251634, -0.03550501, -0.01615001,  0.01875639,  0.00594487],
       [ 0.01300612, -0.01196738, -0.00519123, -0.0150033 ,  0.03097718,
         0.028545  , -0.01906031,  0.0456144 ,  0.00068466,  0.01830769],
       [ 0.01654222, -0.01708956, -0.00196649, -0.01984085, -0.0477636 ,
         0.03850544,  0.02906105, -0.04863743, -0.02114741, -0.03485708],
       [-0.04036222, -0.04585977, -0.03898313,  0.03315648, -0.04735288,
         0.00748978, -0.00335581,  0.01694712, -0.0432025 ,  0.02176889],
       [-0.04036222, -0.04585977, -0.03898313,  0.03315648, -0.04735288,
         0.00748978, -0.00335581,  0.01694712, -0.0432025 ,  0.02176889],
       [-0.04036222, -0.04585977, -0.03898313,  0.03315648, -0.04735288,
         0.00748978, -0.00335581,  0.01694712